### ISSUE TITLE
could I run it on ubuntu

### ISSUE THREAD

**Issue by amiltonwong** [abbypa/NNProject_DeepMask#1]
Question: could I run it on ubuntu?

**Comment by abbypa** [comment]
I didn't try, probably yes- most (if not all) of the installations were recommended for linux.
Please update if you succeed :)

**Comment by srbhai** [comment]
I was able to run this HelperScripts/CreateVggGraphWeights.py on ubuntu. Thanks.
Only change you would need is the file paths need to be mentioned as "../resources/vgg16_weights.h5". I mean change the backward slash.

Also the conda commands would vary slightly how you execute them.

**Comment by abbypa** [comment]
Thanks for the update!
