### ISSUE TITLE
Beside reading the source code , is there a convenient instructions for  training custom data? 

### ISSUE THREAD

**Issue by albertyou2** [abbypa/NNProject_DeepMask#11]
Beside reading the source code ,is there a convenient instructions for both using and training custom data? 

Thank you !

**Comment by abbypa** [comment]
I added a general work-flow to the readme page, unfortunately I currently have no other written instructions... Hope this helps.

**Comment by albertyou2** [comment]
Yes it's help! I will try it first ,thanks

**Comment by albertyou2** [comment]
@abbypa I followed the work-flow but met this error at step 3:

sojoyoo@sojoyoo-System-Product-Name:~/nnproject_deepmask/HelperScripts$ sudo /home/sojoyoo/anaconda2/bin/python CreateVggGraphWeights.py 
Using Theano backend.
Using gpu device 0: GeForce GTX 1070 (CNMeM is disabled, cuDNN 5005)
creating graph model...
creating sequential model...
setting graph weights...
Traceback (most recent call last):
  File "CreateVggGraphWeights.py", line 150, in <module>
    graph.set_weights(model.get_weights())
  File "/home/sojoyoo/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 1999, in set_weights
    for layer in self.layers:
AttributeError: 'Graph' object has no attribute 'layers'

my keras version is 1.11.1, theano is 0.9.0, should I install keras 0.8.0 as the same as yours?

**Comment by abbypa** [comment]
Yes, it's a Keras version issue.
See #3 #5 #7 
Using my version (0.3.1) should solve it.
