### ISSUE TITLE
ExamplesGenerator not generating examples

### ISSUE THREAD

**Issue by maximus009** [abbypa/NNProject_DeepMask#13]
Hi,
All the input images identified result in segments being too small or too big for the image. None of the image/segmentation goes past that check.
Output of stats:
`imgs found: 164`
`imgs with illegal annotations: 12`
`imgs with legal annotations: 152`
`seg too big: 385`
`seg too small: 495`
`seg too close to the edges: 2`
`seg success: 0`

everything else is 0...
What could be the issue?

**Comment by abbypa** [comment]
Did you use the MSCOCO image corpus without rescaling?
It is possible that some images don't have the correct object size, try using more images, perhaps.

**Comment by maximus009** [comment]
I download the images using coco.download(). Is there any rescaling that needs to be done?
Following your advice, I downloaded a lot more images, and now it is fine.
- Thanks!
