### ISSUE TITLE
EndToEnd.py can't find images

### ISSUE THREAD

**Issue by recluze** [abbypa/NNProject_DeepMask#19]
I followed the steps given in the readme. Got some examples generated through `ExampleGenerator.py`. However, it seems that `EndToEnd.py` can't find them. Sifting through the code, I could gather that `ExamplesGenerator.py` is writing to `Results/pos-train` and `Results/neg-train` whereas `EndToEnd.py` is trying to read from `Predictions/train`. Is there a missing step in the readme where we need to move files to the correct folder or is there some other error? 

(For details, the error I'm getting in `EndToEnd.py` is the empty list when trying to stack images.) 

p.s. Thanks a lot for putting in the effort to make this code available and for pointing to the pre-trained models.

**Comment by abbypa** [comment]
Yes, you are correct- you should create a Predictions/train folder with the examples to train on.
You can choose your own ratio of positive vs. negative examples.
I'll add this to the readme file, thank you!

**Comment by dav-sap** [comment]
hey @abbypa 
Why would I want to use negative examples in my Predictions/Train folder? 
and how will the code know to learn that these are neg examples\pos examples?

**Comment by jgmatu** [comment]
Hi,

Two questions,

¿How Can I interpret the results?

¿How Can I see the category that is marked from one input on the network?

Thanks,
