### ISSUE TITLE
CreateVggGraphWeights.py error

### ISSUE THREAD

**Issue by zhengxuyu** [abbypa/NNProject_DeepMask#5]
I am tried to run your code. However, I got the for layer in self.layers: “AttributeError: 'Graph' object has no attribute 'layers' ”error. when I running CreateVggGraphWeights.py,

**Comment by JieChen91** [comment]
Hi, did you address that problem?

**Comment by abbypa** [comment]
Solved by installing version 0.3.1 of keras (see issue #3 )
