### ISSUE TITLE
Error allocating device memory

### ISSUE THREAD

**Issue by zhengxuyu** [abbypa/NNProject_DeepMask#6]
Hi guys,

I got this error when I try to do the training. The Traceback show below:
Error allocating 411041792 bytes of device memory < out of memory >. Driver report 169512960 bytes free and 2147483648 bytes total
Have you encounter this problem before? May I ask what size your GPU memory is?

Regards,
Zhengxu

**Comment by abbypa** [comment]
I ran on CPU (on a 8 GB RAM computer) and not GPU, I think this is the default, see here-
http://keras.io/getting-started/faq/#how-can-i-run-keras-on-gpu

It does need a lot of memory, and it seems you don't have enough- maybe there is something else running that is memory-consuming?

**Comment by zhengxuyu** [comment]
Hi,

I solved it yesterday, set the 'optimizer = None' in Theano's setting and then recreate the net. But it will slow the process
And ran it on CPU works as well

**Comment by abbypa** [comment]
Cool :) I guess it's a memory-cpu trade off, to be chosen according to available hardware. Good to know.
