### ISSUE TITLE
Is EndToEnd.py the entrance for the whole project?

### ISSUE THREAD

**Issue by JieChen91** [abbypa/NNProject_DeepMask#7]
Hi,
I try to first run EndToEnd.py to see how the project works, but there are many pre-set paths, like Resources and Predictions containing other files that are not originally in the repository. Does that mean I have to generate those paths and files in advance by myself?

For example, to obtain 'Resources/vgg16_graph_weights.h5', I need to run HelperScripts/CreateVggGraphWeights.py. However, I get a bug there saying "'Graph' object has no attribute 'layers'", occurred at line 150 (graph.set_weights(model.get_weights())).

Can anyone help? Thanks~

**Comment by zhengxuyu** [comment]
Yes, indeed, you need to generate those files before you run EndToEnd.py. And download the Coco dataset as well.
For the example, you need to install Keras 0.3.1 to solve this problem
You can read the closed issue to get some idea

**Comment by abbypa** [comment]
That's correct.

In general, you need to-
1. Install all requirements, as listed in the readme
2. Download mscoco annotations (see readme link)
3. Download and convert graph weights with HeplerScripts/CreateVggGraphWeights.py  (see readme link)
4. Create the learning dataset using ExamplesGenerator.py
5. Run EndToEnd.py :)

And the other issue you described is indeed a keras version issue.
