### ISSUE TITLE
Train loss and test loss are both NaN

### ISSUE THREAD

**Issue by doujiang-zheng** [abbypa/NNProject_DeepMask#8]
- Firstly, I download 500 pictures to run ExampleGenerator.py, then generate image and mask.
  Copy them into Predictions' test and train directory. When EndToEnd.py finishes its task, train_loss and test_loss are both NaN. What does this NaN come from, the numeric computation error or some setting errors?
- Secondly, MSCOCO image set are downloaded in the server, but when I run EndToEnd.py, it rapidly used 80% of the memory and was killed by the system. Are there still some settings errors? 
- The server runs at CentOS 7.1.1503. MSCOCO has 82783 images at all. ExampleGenerator.py generates 49740 images in neg-train and 56956 images in pos-train. I copy them all into the directory Predictions/train.
- Thanks for your code!

**Comment by abbypa** [comment]
1. NaN- Try to play with the learning parameters, like learning rate, decay, momentum etc. (defined in EndToEnd.py).
2. The current code is indeed very memory consuming... You may try running with less examples, or maybe create a code version that caches less images simultaneously.

Good luck!
