### ISSUE TITLE
How to mark the detected object on the original image according the predction output?

### ISSUE THREAD

**Issue by zhengxuyu** [abbypa/NNProject_DeepMask#9]
Hi,

The last question is how to show the detect results on the image, the scores are not visual to show the results.
How to use the predictions['seg_output'] to draw the output image

**Comment by abbypa** [comment]
Hi,

See my answer in issue #4 (first half).
This will save images of the output mask in black & white (not on the original image, but in the same proportion). You can probably write some extra code if you want to overlay the mask and the image.

Note that the output is smaller than the original input- the paper uses an additional final layer of bilinear upsampling, I did the opposite while learning, and down-scaled the expected output to the smaller scale.

**Comment by zhengxuyu** [comment]
Thank you!
